#!/bin/bash
set +x

MARLIN_CACHE=$PWD/cache
MARLIN="Marlin"

MARLIN_LOCKFILE=.marlin.lock
MARLIN_CURRENT_LOCKFILE=.marlin.current.lock

if [ -z $MARLIN_VERSION ]; then
  if [ -e $1 ]; then
      echo "Sourcing desired Marlin version from $MARLIN_LOCKFILE"
      MARLIN_VERSION=$(cat .marlin.lock)
  else
      echo "Sourcing desired Marlin version from argument"
      MARLIN_VERSION=$1
  fi 
fi

echo "Desired Marlin version is $MARLIN_VERSION"

MARLIN_DOWNLOAD_URL="https://codeload.github.com/MarlinFirmware/Marlin/tar.gz/$MARLIN_VERSION"

if [ ! -e $MARLIN_CACHE ]; then
    echo "Creating cache folder..."
    mkdir -p $MARLIN_CACHE
fi

if [ ! -e $MARLIN_CACHE/$MARLIN_VERSION.tar.gz ]; then
    echo "Downloading Marlin $MARLIN_VERSION from $MARLIN_DOWNLOAD_URL..."
    curl $MARLIN_DOWNLOAD_URL -o $MARLIN_CACHE/$MARLIN_VERSION.tar.gz 
fi

if [ ! -e $MARLIN_CURRENT_LOCKFILE ]; then
    echo "Current Marlin version in directory is not specified."
    echo 0 > $MARLIN_CURRENT_LOCKFILE
else
	echo "Current Marlin version in directory is $(cat $MARLIN_CURRENT_LOCKFILE)"
fi

# Check the lock file to see what version of Marlin is currently
# configured.
if [ ! -e $MARLIN ] || ! grep -q "$MARLIN_VERSION" "$MARLIN_CURRENT_LOCKFILE" || ! grep -q "$MARLIN_VERSION" "$MARLIN_LOCKFILE"; then
    echo "Initializing Marlin directory to $MARLIN_VERSION..."

    rm -rf Marlin
    tar xf $MARLIN_CACHE/$MARLIN_VERSION.tar.gz
    mv Marlin-$MARLIN_VERSION $MARLIN

    # Set up symlinks for configuration
    # files stored outside of the Marlin tree
    cp -f --symbolic-link $PWD/configs/* $PWD/Marlin/Marlin
    echo $MARLIN_VERSION > $MARLIN_LOCKFILE
    echo $MARLIN_VERSION > $MARLIN_CURRENT_LOCKFILE
fi

echo "Done!"
